import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
<<<<<<< HEAD
  title: 'Create Next App',
  description: 'Generated by create next app',
=======
  title: 'Ansh Vashisth',
>>>>>>> ec44cf6106d7ab1ae9f0a89bee42d29efa85ff68
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
